### ISSUE TITLE
ysws.hackclub.com is broken when trying to parse the programs.json

### ISSUE THREAD

**Issue by sillyangel** [PawiX25/YSWS-Catalog#6]
![image](https://github.com/user-attachments/assets/bacf3451-74a4-4c0c-b1ad-877b10b5cbdb)

it seems you haven't updated the website since the given that the demo's URL works, but not the hackclub.com URL, and that the URL is missing the "ended" for the completed array

**Comment by PawiX25** [comment]
Hi, sorry about the issue! I updated my fork but forgot to sync the changes to the Hack Club's fork. I'll get it fixed right away. Thanks for catching this, and sorry for the inconvenience!
